import fetch from 'node-fetch'
import fs from 'fs/promises'
import path from 'path'

const LINKEDIN_VERSION = process.env.LINKEDIN_VERSION || '202606'
const LINKEDIN_BASE_URL = 'https://api.linkedin.com/rest'

function normalizeToken(token = '') {
  return String(token).trim().replace(/^['"]|['"]$/g, '')
}

function getAuthorUrn() {
  if (process.env.LINKEDIN_AUTHOR_URN) return process.env.LINKEDIN_AUTHOR_URN.trim()
  if (process.env.LINKEDIN_ORGANIZATION_ID) return `urn:li:organization:${String(process.env.LINKEDIN_ORGANIZATION_ID).trim()}`
  if (process.env.LINKEDIN_PERSON_ID) return `urn:li:person:${String(process.env.LINKEDIN_PERSON_ID).trim()}`
  return ''
}

function getConfig() {
  const accessToken = normalizeToken(process.env.LINKEDIN_ACCESS_TOKEN)
  const author = getAuthorUrn()

  if (!accessToken || !author) {
    const err = new Error('LinkedIn posting is not configured. Add LINKEDIN_ACCESS_TOKEN and LINKEDIN_AUTHOR_URN, or LINKEDIN_ORGANIZATION_ID, in backend/.env.')
    err.status = 400
    throw err
  }

  return { accessToken, author }
}

function isVideoUrl(url = '') {
  return /\.(mp4|mov)(\?|#|$)/i.test(url)
}

function isImageUrl(url = '') {
  return /\.(jpe?g|png|gif)(\?|#|$)/i.test(url)
}

function assertPublicLinkedInMediaUrl(mediaUrl) {
  let parsed
  try {
    parsed = new URL(mediaUrl)
  } catch {
    const err = new Error('LinkedIn media URL is invalid.')
    err.status = 400
    throw err
  }

  if (parsed.protocol !== 'https:') {
    const err = new Error('LinkedIn requires a public HTTPS media URL. Set BACKEND_PUBLIC_URL to your public HTTPS backend URL, or paste a public media URL.')
    err.status = 400
    throw err
  }

  if (/^(localhost|127\.|0\.0\.0\.0)/i.test(parsed.hostname)) {
    const err = new Error('LinkedIn cannot access localhost media. Use a public HTTPS URL for uploaded media.')
    err.status = 400
    throw err
  }
}

function linkedInHeaders(accessToken, extra = {}) {
  return {
    Authorization: `Bearer ${accessToken}`,
    'Linkedin-Version': LINKEDIN_VERSION,
    'X-Restli-Protocol-Version': '2.0.0',
    ...extra,
  }
}

async function linkedInPost(path, body, accessToken) {
  const res = await fetch(`${LINKEDIN_BASE_URL}/${path}`, {
    method: 'POST',
    headers: linkedInHeaders(accessToken, { 'Content-Type': 'application/json' }),
    body: JSON.stringify(body),
  })
  const data = await res.json().catch(() => ({}))

  if (!res.ok) {
    const err = new Error(data.message || data.error_description || `LinkedIn API error (${res.status})`)
    err.status = res.status
    throw err
  }

  return { ...data, id: res.headers.get('x-restli-id') || data.id }
}

async function readGeneratedMediaFromDisk(mediaUrl) {
  let parsed
  try {
    parsed = new URL(mediaUrl)
  } catch {
    return null
  }

  if (!parsed.pathname.startsWith('/generated/')) return null

  const generatedRoot = path.resolve(process.cwd(), 'generated')
  const filePath = path.resolve(process.cwd(), `.${decodeURIComponent(parsed.pathname)}`)
  if (!filePath.startsWith(generatedRoot)) return null

  return fs.readFile(filePath)
}

async function getMediaBytes(mediaUrl) {
  try {
    const media = await fetch(mediaUrl)
    if (media.ok) return Buffer.from(await media.arrayBuffer())
  } catch {
    // Fall back to disk for files generated by this backend.
  }

  const localBytes = await readGeneratedMediaFromDisk(mediaUrl)
  if (localBytes) return localBytes

  throw new Error('Could not fetch media for LinkedIn upload.')
}

async function uploadImage(mediaUrl, accessToken, author) {
  assertPublicLinkedInMediaUrl(mediaUrl)
  if (!isImageUrl(mediaUrl)) {
    const err = new Error('LinkedIn image posting supports JPG/JPEG/PNG/GIF images.')
    err.status = 400
    throw err
  }

  const init = await linkedInPost('images?action=initializeUpload', {
    initializeUploadRequest: { owner: author },
  }, accessToken)

  const uploadUrl = init.value?.uploadUrl
  const imageUrn = init.value?.image
  if (!uploadUrl || !imageUrn) throw new Error('LinkedIn did not return an image upload URL.')

  const bytes = await getMediaBytes(mediaUrl)

  const upload = await fetch(uploadUrl, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${accessToken}` },
    body: bytes,
  })
  if (!upload.ok) throw new Error(`LinkedIn image upload failed (${upload.status}).`)

  return imageUrn
}

function postBody({ author, caption, mediaUrn }) {
  return {
    author,
    commentary: caption,
    visibility: 'PUBLIC',
    distribution: {
      feedDistribution: 'MAIN_FEED',
      targetEntities: [],
      thirdPartyDistributionChannels: [],
    },
    ...(mediaUrn ? { content: { media: { id: mediaUrn } } } : {}),
    lifecycleState: 'PUBLISHED',
    isReshareDisabledByAuthor: false,
  }
}

export async function publishLinkedInPost({ caption, mediaUrl, type }) {
  const { accessToken, author } = getConfig()

  if (mediaUrl && (type === 'Video' || isVideoUrl(mediaUrl))) {
    const err = new Error('LinkedIn video posting is not enabled in this app yet. Use text or image posts.')
    err.status = 400
    throw err
  }

  const mediaUrn = mediaUrl ? await uploadImage(mediaUrl, accessToken, author) : ''
  const published = await linkedInPost('posts', postBody({ author, caption, mediaUrn }), accessToken)
  if (!published.id) throw new Error('LinkedIn did not return a post id.')
  return published
}
